In [2]:
import pandas as pd
import numpy as np

In [3]:
clinical_trials=pd.read_csv(r"C:\Data analyst\healthcare_clinical_analytics_project\healthcare_clinical_analytics_project\02_data_files\clinical_trials.csv")

In [4]:
doctors=pd.read_csv(r"C:\Data analyst\healthcare_clinical_analytics_project\healthcare_clinical_analytics_project\02_data_files\doctors.csv")
doctors

,doctor_id,doctor_name,specialty,hospital_id,years_experience,license_status,hire_date,employment_type
0,1,Dr. Raj Patel,Orthopedics,11,28,Expired,2022-12-25,Full-time
1,2,Dr. David Smith,Endocrinology,20,1,Active,2015-05-22,Full-time
2,3,Dr. Sarah Martin,Orthopedics,20,12,Active,2010-07-26,Full-time
3,4,Dr. Raj Shah,Orthopedics,9,14,Active,2017-09-23,Part-time
4,5,Dr. David Smith,Cardiology,24,19,Active,2012-04-13,Contract
...,...,...,...,...,...,...,...,...
145,146,Dr. Neha Singh,Orthopedics,8,28,Active,2021-07-24,Part-time
146,147,Dr. Neha Patel,Respiratory,2,24,Active,2011-10-20,Full-time
147,148,Dr. David Smith,Endocrinology,14,23,Active,2015-02-08,Full-time
148,149,Dr. Priya Shah,Orthopedics,10,4,Active,2013-03-14,Contract
149,150,Dr. Sarah Brown,Endocrinology,9,10,Active,2017-02-13,Full-time

In [5]:
hospitals=pd.read_csv(r"C:\Data analyst\healthcare_clinical_analytics_project\healthcare_clinical_analytics_project\02_data_files\hospitals.csv")
hospitals.head(5)

,hospital_id,hospital_name,city,province,hospital_type,bed_capacity,accreditation_status,open_date,region
0,1,Ontario Care Hospital 1,Waterloo,ON,General,317,Accredited,2017-03-22,East
1,2,Ontario Care Hospital 2,Mississauga,ON,Specialty,571,Accredited,1992-06-11,Central
2,3,Ontario Care Hospital 3,Hamilton,ON,General,367,Accredited,2013-01-06,Central
3,4,Ontario Care Hospital 4,Hamilton,ON,Specialty,494,Accredited,1999-05-23,North
4,5,Ontario Care Hospital 5,Barrie,ON,Research,479,Accredited,2008-06-20,East

In [6]:
medications=pd.read_csv(r"C:\Data analyst\healthcare_clinical_analytics_project\healthcare_clinical_analytics_project\02_data_files\medications.csv")
medications

,medication_id,medication_name,drug_class,manufacturer,unit_cost,approval_status,side_effect_risk,created_date
0,1,Med-001,Beta Blocker,HealthGen,393.93,Approved,Low,2022-07-08
1,2,Med-002,Antibiotic,BioNova,169.99,Approved,Medium,2022-09-01
2,3,Med-003,Analgesic,MediCore,191.34,Discontinued,Medium,2021-06-25
3,4,Med-004,Beta Blocker,MediCore,34.42,Discontinued,Medium,2024-05-23
4,5,Med-005,Analgesic,CareLabs,83.17,Approved,High,2023-06-09
...,...,...,...,...,...,...,...,...
115,116,Med-116,Beta Blocker,CareLabs,211.59,Approved,Medium,2023-05-24
116,117,Med-117,Beta Blocker,MediCore,339.71,Trial,Low,2022-12-07
117,118,Med-118,Antiviral,BioNova,64.96,Trial,Medium,2024-01-28
118,119,Med-119,Beta Blocker,HealthGen,313.20,Discontinued,Medium,2021-11-02
119,120,Med-120,Beta Blocker,BioNova,391.29,Approved,Medium,2023-07-20

In [7]:
patients=pd.read_csv(r"C:\Data analyst\healthcare_clinical_analytics_project\healthcare_clinical_analytics_project\02_data_files\patients.csv")
patients

,patient_id,first_name,last_name,gender,age,city,province,signup_date,primary_condition,risk_level
0,1,Mia,Brown,Other,18.0,Barrie,ON,2024-08-22,Hypertension,Medium
1,2,Olivia,Singh,Female,39.0,Toronto,ON,2023-04-15,Diabetes,High
2,3,Lucas,Martin,Male,31.0,Kitchener,ON,2024-10-03,Hypertension,Low
3,4,Emma,Khan,Female,62.0,Barrie,ON,2025-02-22,Hypertension,Low
4,5,Mia,Khan,Female,23.0,Barrie,ON,2024-06-09,Kidney Disease,Low
...,...,...,...,...,...,...,...,...,...,...
4995,4996,Mia,Shah,Male,55.0,London,ON,2023-03-23,Diabetes,Low
4996,4997,Olivia,Martin,Male,54.0,Mississauga,ON,2023-08-05,Kidney Disease,Medium
4997,4998,Emma,Singh,Female,62.0,Barrie,ON,2023-12-01,Cardiac,Medium
4998,4999,Noah,Martin,Female,51.0,Windsor,ON,2024-07-12,Kidney Disease,High
4999,5000,Olivia,Khan,Male,19.0,Waterloo,ON,2025-05-13,Migraine,Medium

In [8]:
treatments=pd.read_csv(r"C:\Data analyst\healthcare_clinical_analytics_project\healthcare_clinical_analytics_project\02_data_files\treatments.csv")

In [9]:
treatments

,treatment_id,patient_id,trial_id,doctor_id,hospital_id,medication_id,treatment_group,treatment_date,dosage_mg,visit_type
0,1,3315,53,113,10,87,Test,2024-03-03,200,Follow-up
1,2,1492,21,85,18,72,Test,2024-07-22,50,Follow-up
2,3,4554,46,115,25,22,Control,2024-09-18,200,Initial
3,4,2602,32,44,7,90,Control,2024-09-10,50,Routine
4,5,2261,32,129,4,83,Control,2025-04-15,50,Routine
...,...,...,...,...,...,...,...,...,...,...
8995,8996,3197,3,8,12,26,Test,2024-12-20,10,Initial
8996,8997,3373,20,60,11,30,Test,2024-07-02,200,Follow-up
8997,8998,4748,3,42,21,2,Test,2024-06-09,25,Routine
8998,8999,1647,6,144,16,115,Test,2024-06-07,5,Initial
8999,9000,3142,29,101,7,18,Control,2025-03-27,10,Follow-up

In [10]:
trial_results=pd.read_csv(r"C:\Data analyst\healthcare_clinical_analytics_project\healthcare_clinical_analytics_project\02_data_files\trial_results.csv")

In [11]:
trial_results

,result_id,patient_id,trial_id,doctor_id,hospital_id,treatment_group,result_date,success,recovery_days,side_effect,patient_satisfaction_score,follow_up_required
0,1,1791,55,87,20,Test,2024-10-08,1,41,Mild,10.0,Yes
1,2,873,59,59,6,Control,2024-07-14,1,28,Mild,7.6,No
2,3,4661,44,94,11,Test,2025-12-31,1,33,NaN,6.8,No
3,4,4487,16,73,4,Test,2025-02-06,0,65,NaN,8.3,No
4,5,1063,53,89,17,Test,2024-05-11,0,41,NaN,6.7,No
...,...,...,...,...,...,...,...,...,...,...,...,...
11995,11996,4152,36,103,25,Control,2025-08-21,0,47,NaN,7.6,Yes
11996,11997,586,26,117,4,Control,2025-03-18,1,55,Moderate,5.0,Yes
11997,11998,2992,44,19,15,Test,2025-10-29,1,31,Moderate,9.4,Yes
11998,11999,3302,59,29,18,Test,2025-01-11,1,43,NaN,6.5,No
11999,12000,3140,47,34,15,Test,2024-03-26,1,43,Mild,7.5,No

In [12]:
import pandas as pd
from sqlalchemy import create_engine

In [13]:
engine = create_engine(
    "postgresql+psycopg2://postgres:727472@Uv@localhost:5432/healthcare"
)
engine

Engine(postgresql+psycopg2://postgres:***@Uv@localhost:5432/healthcare)

In [14]:
df = pd.read_csv(r"C:\Data analyst\healthcare_clinical_analytics_project\healthcare_clinical_analytics_project\02_data_files\patients.csv")

df.to_sql("patients", engine, index=False, if_exists="replace")

print("Done")

OperationalError: (psycopg2.OperationalError) could not translate host name "Uv@localhost" to address: Non-recoverable failure in name resolution

(Background on this error at: https://sqlalche.me/e/20/e3q8)

In [ ]:
from sqlalchemy import create_engine, text

engine = create_engine(
    "postgresql+psycopg2://postgres:727472@Uv@localhost:5432/healthcare"
)

with engine.connect() as conn:
    result = conn.execute(text("SELECT 1"))
    print(result.fetchone())

In [ ]:
import pandas as pd
from sqlalchemy import create_engine
from urllib.parse import quote_plus

password = quote_plus("727472@Uv")

engine = create_engine(
    f"postgresql+psycopg2://postgres:{password}@localhost:5432/healthcare"
)

df = pd.read_csv(r"C:\Data analyst\healthcare_clinical_analytics_project\healthcare_clinical_analytics_project\02_data_files\patients.csv")

df.to_sql("patients", engine, index=False, if_exists="replace")

print("Done")

In [ ]:
SELECT COUNT(*) FROM patients;

In [ ]:
folder = r"C:\Data analyst\healthcare_clinical_analytics_project\healthcare_clinical_analytics_project\02_data_files"



tables = [
    "patients",
    "hospitals",
    "doctors",
    "medications",
    "clinical_trials",
    "treatments",
    "trial_results"
]


for table in tables:
    file_path = folder + "\\" + table + ".csv"
    df = pd.read_csv(file_path)
    df.to_sql(table, engine, index=False, if_exists="replace")
    print(table, "loaded")

In [ ]:
dataframes = {
    "patients": patients,
    "treatments": treatments,
    "trial_results": trial_results,
    "clinical_trials": clinical_trials,
    "doctors": doctors,
    "hospitals": hospitals,
    "medications": medications
}

for name, df in dataframes.items():
    print("=" * 50)
    print(name.upper())
    print("Shape:", df.shape)
    print("Columns:", df.columns.tolist())
    display(df.head())

In [ ]:
patients.isnull().sum()

In [ ]:
trial_results.isnull().sum()

In [ ]:
patients["city"]=patients["city"].fillna("Uknow")

In [ ]:
patients["age"]=patients["age"].fillna(patients["age"].median())

In [ ]:
trial_results["side_effect"] = trial_results["side_effect"].fillna("Unknown")

In [ ]:
trial_results["patient_satisfaction_score"] = trial_results["patient_satisfaction_score"].fillna(
    trial_results["patient_satisfaction_score"].mean()
)

In [ ]:
patients["full_name"]=patients["first_name"]+" "+patients["last_name"]

In [ ]:
patients

In [ ]:
patients[["first_name", "last_name", "full_name"]].head()

In [ ]:
merged_df=pd.merge(patients,trial_results,on="patient_id",how="inner")

In [ ]:
merged_df

In [ ]:

final_df=pd.merge(

       merged_df,clinical_trials,on="trial_id",how="inner"
    
)


final_df=pd.merge(

    final_df,hospitals,on="hospital_id",how="inner"
)

In [ ]:
final_df

In [ ]:
final_df.to_csv("final_healthcare_analysis.csv",index=False)

In [ ]:
import os
os.path.exists("final_healthcare_analysis.csv")

In [ ]:
success_rate=final_df.groupby("treatment_group")["success"].mean()*100
success_rate

In [ ]:
control=success_rate["Control"]

In [ ]:
test=success_rate["Test"]

In [ ]:
improvement=((test-control)/control)*100
improvement

In [ ]:
final_df.groupby("treatment_group")["recovery_days"].mean()

In [ ]:
final_df.groupby("treatment_group")["patient_satisfaction_score"].mean()

In [ ]:
def healthcare_pipeline():
    import pandas as pd
    base_path = r"C:\Data analyst\healthcare_clinical_analytics_project\healthcare_clinical_analytics_project\02_data_files"
    # Load data
    patients = pd.read_csv(base_path + "\\patients.csv")
    treatments = pd.read_csv(base_path + "\\treatments.csv")
    trial_results = pd.read_csv(base_path + "\\trial_results.csv")
    clinical_trials = pd.read_csv(base_path + "\\clinical_trials.csv")
    doctors = pd.read_csv(base_path + "\\doctors.csv")
    hospitals = pd.read_csv(base_path + "\\hospitals.csv")
    medications = pd.read_csv(base_path + "\\medications.csv")
    # Clean data
    patients["city"] = patients["city"].fillna("Unknown")
    patients["age"] = patients["age"].fillna(patients["age"].median())
    trial_results["side_effect"] = trial_results["side_effect"].fillna("Unknown")
    trial_results["patient_satisfaction_score"] = trial_results["patient_satisfaction_score"].fillna(
        trial_results["patient_satisfaction_score"].mean()
    )

    # Feature engineering
    patients["full_name"] = patients["first_name"] + " " + patients["last_name"]

    # Merge data
    df = pd.merge(patients, trial_results, on="patient_id", how="inner")
    df = pd.merge(df, clinical_trials, on="trial_id", how="inner")
    df = pd.merge(df, hospitals, on="hospital_id", how="inner")

    # Export data
    df.to_csv("f_healthcare_analysis.csv", index=False)

    return df

In [ ]:
final_df=healthcare_pipeline()

In [ ]:
final_df

In [ ]:
import pandas as pd
from sqlalchemy import create_engine

password = "727472%40Uv"   # @ → %40

engine = create_engine(
    f"postgresql+psycopg2://postgres:{password}@localhost:5432/healthcare_clinical_analytics_project"
)

In [ ]:
patients.isnull().sum()

In [ ]:
engine

In [ ]:
patients.to_sql("patients",engine,if_exists="replace",index=False)

In [ ]:
treatments.to_sql("treatments", engine, if_exists="replace", index=False)
trial_results.to_sql("trial_results", engine, if_exists="replace", index=False)
clinical_trials.to_sql("clinical_trials", engine, if_exists="replace", index=False)
doctors.to_sql("doctors", engine, if_exists="replace", index=False)
hospitals.to_sql("hospitals", engine, if_exists="replace", index=False)

In [ ]:
patients.shape

In [ ]:
patients.to_csv("patients_cleaned.csv", index=False)

In [17]:
import pandas as pd
from sqlalchemy import create_engine
from sqlalchemy.engine import URL

# 1. Create PostgreSQL connection
url = URL.create(
    drivername="postgresql+psycopg2",
    username="postgres",
    password="727472@Uv",
    host="localhost",
    port=5432,
    database="healthcare_clinical_analytics_project"
)

engine = create_engine(url)

In [19]:
# 2. Load original CSV files
folder_path = r"C:\Data analyst\healthcare_clinical_analytics_project\healthcare_clinical_analytics_project\02_data_files"

patients = pd.read_csv(folder_path + r"\patients.csv")
treatments = pd.read_csv(folder_path + r"\treatments.csv")
trial_results = pd.read_csv(folder_path + r"\trial_results.csv")
clinical_trials = pd.read_csv(folder_path + r"\clinical_trials.csv")
doctors = pd.read_csv(folder_path + r"\doctors.csv")
hospitals = pd.read_csv(folder_path + r"\hospitals.csv")

In [20]:
# 3. Clean patients table
patients["city"] = patients["city"].fillna("Unknown")
patients["age"] = patients["age"].fillna(patients["age"].median())

patients["full_name"] = patients["first_name"] + " " + patients["last_name"]

In [21]:
# 4. Clean trial_results table
trial_results["side_effect"] = trial_results["side_effect"].fillna("Unknown")

trial_results["patient_satisfaction_score"] = trial_results["patient_satisfaction_score"].fillna(
    trial_results["patient_satisfaction_score"].mean()
)

In [25]:
# 5. Save cleaned CSV files
cleaned_folder = r"C:\Data analyst\healthcare_clinical_analytics_project\healthcare_clinical_analytics_project\03_cleaned_files"

patients.to_csv(cleaned_folder + r"\patients_cleaned.csv", index=False)
treatments.to_csv(cleaned_folder + r"\treatments_cleaned.csv", index=False)
trial_results.to_csv(cleaned_folder + r"\trial_results_cleaned.csv", index=False)
clinical_trials.to_csv(cleaned_folder + r"\clinical_trials_cleaned.csv", index=False)
doctors.to_csv(cleaned_folder + r"\doctors_cleaned.csv", index=False)
hospitals.to_csv(cleaned_folder + r"\hospitals_cleaned.csv", index=False)

print("Cleaned CSV files saved successfully.")

Cleaned CSV files saved successfully.